<?php

namespace WE\PlatformBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdverts($page, $nbPerPage)
    {
        $o_query = $this->createQueryBuilder('ad')
            // Jointure
            ->leftJoin('ad.image', 'im')
            ->addSelect('im')
            ->leftJoin('ad.categories', 'ca')
            ->addSelect('ca')
            ->leftJoin('ad.applications', 'ap')
            ->addSelect('ap')
            ->leftJoin('ad.advertSkills', 'sk')
            ->addSelect('sk')
            // Next
            ->orderBy('ad.date', 'DESC')
            ->getQuery()
            // Pagination
            ->setFirstResult(($page-1)*$nbPerPage)
            ->setMaxResults($nbPerPage)
        ;
        
        return new Paginator($o_query, true);
    }
    
    public function isFlood($ip, $secondes)
    {
        $qb = $this->createQueryBuilder('ad')
            ->select('COUNT(ad.id)')
            ->where('ad.ip = :ip')
            ->setParameter('ip', $ip)
            ->andWhere('ad.updatedAt >= :date')
            ->setParameter('date', new \Datetime('-'.$secondes.'seconds'))
        ;
        
        return (bool) $qb->getQuery()->getSingleScalarResult();
    }
}
