<?php

namespace WE\TestBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function myFindAll() 
    {
        // Méthode 1 : en passant par l'EntityManager
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('page')
            ->from($this->_entityName, 'page')
        ;
        
        // Dans un repository, $this->_entityName est le namespace de l'entité gérée
        // Ici, il vaut donc OC\PlatformBundle\Entity\Advert
        // Méthode 2 : en passant par le raccourci (je recommande)
        $queryBuilder = $this->createQueryBuilder('page');
        
        // On n'ajoute pas de critère ou tri particulier, la construction
        // de notre requête est finie
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        
        // On retourne ces résultats
        return $results;
    }
    
    public function myFindOne($id)
    {
        $queryBuilder = $this->createQueryBuilder('page');
        
        $queryBuilder->where('page.id=:id')->setParameter('id', $id);
        
        return $queryBuilder->getQuery()->getSingleResult();
    }
    
    public function getPageDataByUrl($url)
    {
        $queryBuilder = $this
            ->createQueryBuilder('page')
            ->leftJoin('page.pageDatas', 'pds')
            ->where('pds.url = :url')
            ->setParameter('url', $url)
            ->addSelect('pds')
        ;
        
        return $queryBuilder
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
