<?php

namespace WE\TestBundle\Repository;

use WE\TestBundle\Entity\Page;
use WE\TestBundle\Entity\PageData;

/**
 * PageDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindOneData($url)
    {
        $queryBuilder = $this->createQueryBuilder('pageData');
        
        $queryBuilder->where('pageData.url=:url')->setParameter('url', $url);
        
        return $queryBuilder->getQuery()->getSingleResult();
    }
    
    public function getPageDataByUrl($s_url)
    {
        $queryBuilder = $this
            ->createQueryBuilder('pageData')
            ->leftJoin('pageData.page', 'page')
            ->addSelect('page')
            ->where('page.url=:url')->setParameter('url', $s_url)
        ;
        
        return $queryBuilder->getQuery()->getSingleResult();
    }
    
    public function getPageDataById($a_params)
    {
        $queryBuilder = $this
            ->createQueryBuilder('pageData')
            ->leftJoin('pageData.page', 'page')
            ->addSelect('page')
            ->where('page.id=:id')->setParameter('id', $a_params['id'])
            ->andWhere('page.status=:status_page')->setParameter('status_page', Page::ENABLE)
            ->andWhere('pageData.status = :status_page_data')->setParameter('status_page_data', PageData::ENABLE)
        ;
                
        if (isset($a_params['lang'])) {
            $queryBuilder->andWhere('pageData.lang=:lang')->setParameter('lang', $a_params['lang']);
            
            return $queryBuilder->getQuery()->getSingleResult();
        } else {
            if (isset($a_params['toArray']))
                return $queryBuilder->getQuery()->getArrayResult();
            else 
                return $queryBuilder->getQuery()->getResult();
        }
    }
}
