<?php

namespace WE\TestBundle\Repository;

/**
 * TestServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
